const STORAGE_KEY='uffda.live-orders.session.v1';
const runtime=()=>window.__UFFDA_LIVE_ORDERS__||{};
const required=(name,value)=>{if(!value)throw new Error(`${name} is not configured`);return value;};
const supabaseUrl=()=>required('SUPABASE_URL',(runtime().SUPABASE_URL||import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,''));
const anonKey=()=>required('SUPABASE_PUBLISHABLE_KEY',runtime().SUPABASE_PUBLISHABLE_KEY||runtime().SUPABASE_ANON_KEY||import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY);

function authHeaders(token,extra={}){return{apikey:anonKey(),Authorization:`Bearer ${token}`,'Content-Type':'application/json',...extra};}
export function loadLiveSession(){try{return JSON.parse(sessionStorage.getItem(STORAGE_KEY)||'null');}catch{return null;}}
export function saveLiveSession(session){sessionStorage.setItem(STORAGE_KEY,JSON.stringify(session));}
export function clearLiveSession(){sessionStorage.removeItem(STORAGE_KEY);}
export async function signInStaff(username,password){const response=await fetch(`${supabaseUrl()}/functions/v1/orders-api/login`,{method:'POST',headers:{apikey:anonKey(),'Content-Type':'application/json'},body:JSON.stringify({username,password})});const json=await response.json().catch(()=>({}));if(!response.ok||!json.access_token)throw new Error(json.error||'Staff sign-in failed');const session={accessToken:json.access_token,refreshToken:json.refresh_token,expiresAt:Date.now()+((json.expires_in||3600)*1000)};saveLiveSession(session);return session;}
export async function refreshSession(session){if(!session?.refreshToken)throw new Error('Please sign in again');const response=await fetch(`${supabaseUrl()}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:anonKey(),'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refreshToken})});const json=await response.json().catch(()=>({}));if(!response.ok||!json.access_token){clearLiveSession();throw new Error('Session expired. Please sign in again.');}const next={accessToken:json.access_token,refreshToken:json.refresh_token||session.refreshToken,expiresAt:Date.now()+((json.expires_in||3600)*1000)};saveLiveSession(next);return next;}
export async function ensureSession(session){if(!session?.accessToken)throw new Error('Please sign in');return session.expiresAt-Date.now()<120000?refreshSession(session):session;}
export async function staffStatus(token){const response=await fetch(`${supabaseUrl()}/functions/v1/orders-api/status`,{method:'POST',headers:authHeaders(token),body:'{}'});if(!response.ok)throw new Error('Cannot verify staff authorization');const data=await response.json();return data.authorized===true;}
export async function signOutStaff(session){try{await fetch(`${supabaseUrl()}/auth/v1/logout`,{method:'POST',headers:authHeaders(session.accessToken)});}finally{clearLiveSession();}}
export async function fetchLiveOrders(token){const query='select=id,square_order_id,ticket_number,customer_name,status,payment_status,total_cents,currency,items,source_created_at,created_at,ready_at,updated_at&status=in.(active,ready)&order=source_created_at.asc.nullslast,created_at.asc';const response=await fetch(`${supabaseUrl()}/rest/v1/live_orders?${query}`,{headers:authHeaders(token)});if(response.status===401||response.status===403)throw Object.assign(new Error('Session not authorized'),{code:'AUTH'});const json=await response.json().catch(()=>[]);if(!response.ok)throw new Error(json?.message||'Unable to load orders');return json;}
export async function fetchClearedOrders(token){const query='select=id,ticket_number,customer_name,cleared_at,cleared_from_status&status=eq.cleared&order=cleared_at.desc&limit=50';const response=await fetch(`${supabaseUrl()}/rest/v1/live_orders?${query}`,{headers:authHeaders(token)});const json=await response.json().catch(()=>[]);if(!response.ok)throw new Error(json?.message||'Unable to load cleared orders');return json;}
export async function clearOrders(token,orders){let count=0;for(let start=0;start<orders.length;start+=50){const batch=orders.slice(start,start+50);const ids=batch.map(order=>order.id).join(',');const response=await fetch(`${supabaseUrl()}/rest/v1/live_orders?id=in.(${encodeURIComponent(ids)})&status=in.(active,ready)`,{method:'PATCH',headers:authHeaders(token,{Prefer:'return=representation'}),body:JSON.stringify({status:'cleared'})});const json=await response.json().catch(()=>[]);if(!response.ok)throw Object.assign(new Error(json?.message||'Unable to clear orders'),{cleared:count});count+=json.length;}return count;}
export async function setOrderStatus(token,id,status,previousStatus){const body={status};const response=await fetch(`${supabaseUrl()}/rest/v1/live_orders?id=eq.${encodeURIComponent(id)}&status=eq.${encodeURIComponent(previousStatus)}`,{method:'PATCH',headers:authHeaders(token,{Prefer:'return=representation'}),body:JSON.stringify(body)});const json=await response.json().catch(()=>[]);if(!response.ok)throw new Error(json?.message||'Unable to update order');if(!json.length)throw new Error('Order changed on another device. Refreshing queue.');return json[0];}
export async function requestSquareSync(token,windowMinutes){const response=await fetch(`${supabaseUrl()}/functions/v1/orders-api/sync`,{method:'POST',headers:authHeaders(token),body:JSON.stringify({windowMinutes})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Square sync failed');return json;}
export function subscribeToOrders(token,onChange,onState){let socket=null,heartbeat=null,reconnect=null,attempt=0,closed=false,joined=false;const wsBase=supabaseUrl().replace(/^http/,'ws');const topic='realtime:public:live_orders';const connect=()=>{if(closed)return;onState?.('connecting');socket=new WebSocket(`${wsBase}/realtime/v1/websocket?apikey=${encodeURIComponent(anonKey())}&vsn=1.0.0&access_token=${encodeURIComponent(token)}`);socket.onopen=()=>{attempt=0;const payload={config:{broadcast:{self:false},presence:{key:''},postgres_changes:[{event:'*',schema:'public',table:'live_orders'}]},access_token:token};socket.send(JSON.stringify({topic,event:'phx_join',payload,ref:'1'}));heartbeat=setInterval(()=>socket?.readyState===WebSocket.OPEN&&socket.send(JSON.stringify({topic:'phoenix',event:'heartbeat',payload:{},ref:String(Date.now())})),25000);};socket.onmessage=event=>{let msg;try{msg=JSON.parse(event.data);}catch{return;}if(msg.event==='phx_reply'&&msg.topic===topic){joined=msg.payload?.status==='ok';onState?.(joined?'connected':'reconnecting');if(!joined)socket?.close();return;}if(msg.event==='postgres_changes'||msg.event==='INSERT'||msg.event==='UPDATE'||msg.event==='DELETE')onChange?.(msg);};socket.onerror=()=>onState?.('reconnecting');socket.onclose=()=>{joined=false;clearInterval(heartbeat);if(closed)return;onState?.('reconnecting');reconnect=setTimeout(connect,Math.min(1000*2**attempt++,15000));};};connect();return()=>{closed=true;clearTimeout(reconnect);clearInterval(heartbeat);if(joined&&socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({topic,event:'phx_leave',payload:{},ref:'2'}));socket?.close();};}
