const STORE_KEY = 'ftcc.live.v2';
const LEGACY_KEY = 'ftcc.v1';
const ACTIVE_KEY = 'ftcc.active';
const CHANNEL_NAME = 'ftcc-live-sync';
const CLIENT_ID = createId();
const MONEY_FIELDS = new Set(['gross','discounts','refunds','tax','tips','quote','deposit','amount','total','rate','price','cost','unitCost']);
const MODULES = {
  sales: {title:'Sales Tracker', desc:'Live sales entries that feed dashboard, reports, exports, and profit metrics.', action:'Add Sale', cols:['date','type','location','gross','net','payment','customer','notes'], fields:[['date','Date','date',true],['type','Service Type','select',true,['Lunch','Dinner','Festival','Private Event','Catering','Pop-up','Other']],['location','Location','text'],['gross','Gross Sales','money',true],['discounts','Discounts','money'],['refunds','Refunds','money'],['tax','Sales Tax Collected','money'],['tips','Tips','money'],['payment','Payment Method','select',false,['Card','Cash','Mixed','Online','Invoice','Other']],['customer','Customer / Contact','text'],['notes','Notes','textarea']]},
  customers: {title:'CRM', desc:'Customers, catering leads, contacts, follow-up dates, and pipeline status.', action:'Add Customer', cols:['name','status','type','phone','email','followUp','notes'], fields:[['name','Name / Organization','text',true],['type','Customer Type','select',true,['Walk-up','Catering Lead','Corporate','Event Organizer','Repeat Customer','Referral','Other']],['status','Status','select',true,['New Lead','Contacted','Quoted','Booked','Completed','Active','Lost']],['phone','Phone','tel'],['email','Email','email'],['source','Lead Source','select',false,['Walk-up','Instagram','Facebook','Referral','Website','Google','Event','Other']],['lastContact','Last Contact','date'],['followUp','Next Follow-Up','date'],['notes','Relationship Notes','textarea']]},
  events: {title:'Events & Catering', desc:'Event pipeline, bookings, deposits, balances, guests, menus, and prep notes.', action:'Add Event', cols:['date','name','status','contact','guests','quote','balance','location'], fields:[['name','Event Name','text',true],['date','Event Date','datetime-local',true],['eventType','Event Type','select',true,['Catering','Festival','Corporate Lunch','Private Party','Market','Pop-up','Other']],['status','Status','select',true,['Inquiry','Quoted','Booked','Prep Needed','Completed','Cancelled','Lost']],['contact','Contact Name','text'],['phone','Phone','tel'],['location','Location','text'],['guests','Guest Count','number'],['quote','Quoted Amount','money'],['deposit','Deposit Paid','money'],['menu','Menu Plan','textarea'],['notes','Prep / Service Notes','textarea']]},
  inventory: {title:'Inventory', desc:'Live inventory quantities, reorder points, vendors, cost, expiration, and storage.', action:'Add Inventory Item', cols:['item','category','qty','unit','reorder','stockStatus','unitCost','vendor','expires'], fields:[['item','Item','text',true],['category','Category','select',true,['Protein','Produce','Dairy','Dry Goods','Sauces','Beverages','Paper Goods','Cleaning','Fuel / Propane','Other']],['qty','Current Quantity','number',true],['unit','Unit','select',true,['lb','oz','case','each','gallon','quart','bag','box','tray','other']],['reorder','Reorder Point','number',true],['unitCost','Cost Per Unit','money'],['vendor','Vendor','text'],['expires','Expiration Date','date'],['storage','Storage Area','select',false,['Truck','Commissary','Dry Storage','Freezer','Cooler','Offsite','Other']],['notes','Notes','textarea']]},
  menu: {title:'Menu Costing', desc:'Menu prices, estimated item cost, profit per item, and live margin calculations.', action:'Add Menu Item', cols:['name','category','price','cost','margin','profit','prep','active'], fields:[['name','Menu Item','text',true],['category','Category','select',true,['Entree','Side','Drink','Dessert','Combo','Special','Catering Package']],['price','Sell Price','money',true],['cost','Estimated Food Cost','money',true],['prep','Prep Time Minutes','number'],['active','Active?','select',false,['Yes','No','Seasonal']],['notes','Recipe / Costing Notes','textarea']]},
  purchases: {title:'Purchases', desc:'Vendor purchases, receipt notes, category, costs, and accounting export status.', action:'Add Purchase', cols:['date','vendor','category','item','qty','total','payment','qbo'], fields:[['date','Purchase Date','date',true],['vendor','Vendor','text',true],['category','Category','select',true,['Food Inventory','Packaging','Cleaning','Repairs','Fuel / Propane','Smallwares','Marketing','Other']],['item','Item / Description','text',true],['qty','Quantity','number'],['unit','Unit','text'],['total','Total Cost','money',true],['payment','Payment Method','select',false,['Card','Cash','ACH','Check','Account Credit','Other']],['qbo','Accounting Status','select',false,['Not Ready','Ready to Export','Exported','Needs Review']],['notes','Receipt / Notes','textarea']]},
  vendors: {title:'Vendors', desc:'Supplier records, contacts, categories, terms, and order notes.', action:'Add Vendor', cols:['name','category','contact','phone','email','terms','notes'], fields:[['name','Vendor Name','text',true],['category','Vendor Category','select',true,['Food Supplier','Commissary','Packaging','Repair','Fuel / Propane','Marketing','Insurance','Accounting','Other']],['contact','Contact Name','text'],['phone','Phone','tel'],['email','Email','email'],['terms','Payment Terms','select',false,['Due on Receipt','Net 7','Net 15','Net 30','Card on File','Cash','Other']],['notes','Notes','textarea']]},
  labor: {title:'Labor', desc:'Employee shifts, roles, hours, rates, service assignments, and live labor cost.', action:'Add Shift', cols:['date','employee','role','hours','rate','laborCost','service','notes'], fields:[['date','Date','date',true],['employee','Employee Name','text',true],['role','Role','select',true,['Owner','Cook','Cashier','Prep','Driver','Event Staff','Manager','Other']],['hours','Hours','number',true],['rate','Hourly Rate','money',true],['service','Event / Service','text'],['notes','Notes','textarea']]},
  expenses: {title:'Expenses', desc:'Operating expenses with category, payment method, vendor, notes, and export status.', action:'Add Expense', cols:['date','category','vendor','amount','payment','qbo','notes'], fields:[['date','Date','date',true],['category','Category','select',true,['Fuel','Propane','Commissary Kitchen','Insurance','Permit / License','Truck Repair','Marketing','Software','Professional Services','Supplies','Other']],['vendor','Vendor / Payee','text'],['amount','Amount','money',true],['payment','Payment Method','select',false,['Card','Cash','ACH','Check','Auto-pay','Other']],['qbo','Accounting Status','select',false,['Not Ready','Ready to Export','Exported','Needs Review']],['notes','Notes','textarea']]}
};
const NAV_GROUPS = [['Daily Control',['dashboard','sales','events','reports']],['Business Management',['customers','inventory','menu','purchases']],['Operations',['vendors','labor','expenses','sync','settings']]];
const ICONS = {dashboard:'D',sales:'$',events:'E',reports:'R',customers:'C',inventory:'I',menu:'M',purchases:'P',vendors:'V',labor:'L',expenses:'X',sync:'S',settings:'⚙'};
let state = normalize(readStored() || emptyState());
let active = localStorage.getItem(ACTIVE_KEY) || 'dashboard';
let search = '';
let navOpen = false;
let installPrompt = null;
let lastRenderedRevision = -1;
const channel = 'BroadcastChannel' in window ? new BroadcastChannel(CHANNEL_NAME) : null;
if (!readStored()) persist(state, false);
if (localStorage.getItem(LEGACY_KEY)) localStorage.removeItem(LEGACY_KEY);
window.addEventListener('beforeinstallprompt', event => { event.preventDefault(); installPrompt = event; render(); });
window.addEventListener('storage', event => { if (event.key === STORE_KEY && event.newValue) receiveExternal(event.newValue); });
if (channel) channel.onmessage = event => { if (event.data?.type === 'ftcc-state' && event.data.clientId !== CLIENT_ID) receiveExternal(JSON.stringify(event.data.state)); };
setInterval(() => { const latest = readStored(); if (latest) applyExternal(latest); }, 2500);
render();
registerSW();
function emptyState(){ return { meta:{schemaVersion:2,revision:0,lastSavedAt:null,lastSavedBy:null}, settings:{businessName:'Food Truck Command Center',truckName:'Your Food Truck',taxRate:0,currency:'USD',syncMode:'Local live sync',accountingMode:'Export Only'}, sales:[], customers:[], events:[], inventory:[], menu:[], purchases:[], vendors:[], labor:[], expenses:[] }; }
function normalize(input){ const base=emptyState(); const next={...base,...(input||{}),meta:{...base.meta,...((input||{}).meta||{})},settings:{...base.settings,...((input||{}).settings||{})}}; Object.keys(MODULES).forEach(key=>{ next[key]=Array.isArray(next[key])?next[key]:[]; }); return next; }
function readStored(){ try{ const raw=localStorage.getItem(STORE_KEY); return raw?normalize(JSON.parse(raw)):null; } catch { return null; } }
function persist(next=state, announce=true){ state=normalize(next); localStorage.setItem(STORE_KEY, JSON.stringify(state)); if (announce && channel) channel.postMessage({type:'ftcc-state',clientId:CLIENT_ID,state}); render(); }
function commit(mutator){ const draft=structuredCloneSafe(state); mutator(draft); draft.meta.revision=(Number(draft.meta.revision)||0)+1; draft.meta.lastSavedAt=new Date().toISOString(); draft.meta.lastSavedBy=CLIENT_ID; persist(draft,true); }
function receiveExternal(raw){ try{ applyExternal(normalize(JSON.parse(raw))); } catch {} }
function applyExternal(next){ if (!next) return; const incoming=Number(next.meta?.revision)||0; const current=Number(state.meta?.revision)||0; if (incoming>current || (incoming===current && next.meta?.lastSavedAt && next.meta.lastSavedAt!==state.meta.lastSavedAt)) { state=normalize(next); render(true); } }
function structuredCloneSafe(value){ return typeof structuredClone==='function' ? structuredClone(value) : JSON.parse(JSON.stringify(value)); }
function today(){ return new Date().toISOString().slice(0,10); }
function createId(){ return (crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`); }
function row(values){ return {id:createId(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...values}; }
function setActive(key){ active=key; search=''; navOpen=false; localStorage.setItem(ACTIVE_KEY,key); render(); }
function render(force=false){ if (!force && lastRenderedRevision===state.meta.revision && document.getElementById('root')) return; lastRenderedRevision=state.meta.revision; const [heading,subheading]=pageTitle(); document.getElementById('app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="brand-mark">FT</div><div><h1>${esc(state.settings.truckName)}</h1><p>${syncLabel()}</p></div></div><nav class="nav ${navOpen?'':'collapsed'}">${NAV_GROUPS.map(group=>`<div class="nav-label">${group[0]}</div>${group[1].map(key=>`<button class="nav-btn ${active===key?'active':''}" data-module="${key}"><b>${ICONS[key]}</b><span>${label(key)}</span></button>`).join('')}`).join('')}</nav><div class="side-note"><b>Live system:</b><br/>Every saved record updates dashboards, reports, exports, and any other open tab immediately.</div></aside><main class="main"><section class="topbar"><div><h2>${esc(heading)}</h2><p>${esc(subheading)}</p></div><div class="actions"><button class="btn mobile" data-action="nav">Menu</button><button class="btn" data-action="backup">Backup Data</button><button class="btn" data-action="print">Print / PDF</button>${installPrompt?'<button class="btn orange" data-action="install">Install App</button>':''}</div></section><section id="root">${page()}</section></main></div>`; bind(); }
function pageTitle(){ if(active==='dashboard') return ['Food Truck Command Center','Live operations dashboard built from your actual records only.']; if(active==='reports') return ['Reports','Live reporting from sales, events, inventory, purchases, labor, and expenses.']; if(active==='sync') return ['Live Sync & Accounting','Current sync status, backup tools, and accounting export readiness.']; if(active==='settings') return ['Settings','Business defaults, local data controls, and reset options.']; return [MODULES[active].title,MODULES[active].desc]; }
function page(){ if(active==='dashboard') return dashboard(); if(active==='reports') return reports(); if(active==='sync') return syncPage(); if(active==='settings') return settingsPage(); return tablePage(active); }
function dashboard(){ const m=metrics(), low=lowInventory(), ev=upcomingEvents(), fu=followUps(), insight=menuInsights(); return `<div class="grid4">${card('Today Sales',cash(m.today),'From records dated today.',m.today?'ok':'neutral')}${card('Month Sales',cash(m.sales),'Current calendar month gross sales.','info')}${card('Estimated Profit',cash(m.profit),'Sales minus purchases, labor, and expenses.',m.profit>=0?'ok':'bad')}${card('Low Inventory',String(low.length),'Items at or below reorder point.',low.length?'warn':'ok')}</div><div class="two"><section class="panel"><div class="panel-head"><div><h3>Live Command Board</h3><p>Action items generated from current records.</p></div><button class="btn primary" data-module="sales">Add Sale</button></div><div class="panel-body list">${low.length?low.slice(0,5).map(x=>item(x.item,`${num(x.qty)} ${x.unit||''} on hand. Reorder point: ${num(x.reorder)}.`,'Reorder','warn')).join(''):item('Inventory has no reorder alerts','Add inventory records to activate reorder monitoring.','Live','neutral')}${fu.length?fu.slice(0,5).map(x=>item(x.name,`Follow up by ${fmtDate(x.followUp)}. Status: ${x.status}.`,'Follow Up','info')).join(''):item('No CRM follow-ups due','Add follow-up dates to customer records.','CRM','neutral')}${ev.length?ev.slice(0,5).map(x=>item(x.name,`${fmtDT(x.date)} · ${x.location||'Location TBD'} · ${x.guests||0} guests`,x.status,tone(x.status))).join(''):item('No upcoming events','Add event records to activate the event board.','Events','neutral')}</div></section><section class="panel"><div class="panel-head"><div><h3>Profit Snapshot</h3><p>Calculated live from current month records.</p></div></div><div class="panel-body list">${item('Gross sales',cash(m.sales),'Sales','info')}${item('Purchases',cash(m.purchases),'Purchases','warn')}${item('Labor cost',cash(m.labor),'Labor','warn')}${item('Operating expenses',cash(m.expenses),'Expenses','warn')}${progress('Estimated margin',m.margin)}</div></section></div><div class="two" style="margin-top:18px"><section class="panel"><div class="panel-head"><div><h3>Sales by Service Type</h3><p>Updates whenever sales records change.</p></div></div><div class="panel-body">${bars(groupBy(state.sales,'type','gross'))}</div></section><section class="panel"><div class="panel-head"><div><h3>Menu Margin Watch</h3><p>Calculated from live menu costing records.</p></div></div><div class="panel-body list">${insight.length?insight.map(x=>item(x.name,`${cash(x.profit)} profit/item · ${pct(x.margin)} margin`,x.margin>=65?'Strong':x.margin>=50?'Watch':'Weak',x.margin>=65?'ok':x.margin>=50?'warn':'bad')).join(''):item('No menu costing records','Add menu items to calculate item margins.','Menu','neutral')}</div></section></div>`; }
function tablePage(key){ const def=MODULES[key], rows=filtered(key); return `<section class="panel"><div class="panel-head"><div><h3>${def.title}</h3><p>${state[key].length} live record${state[key].length===1?'':'s'} saved.</p></div><button class="btn primary" data-action="form" data-key="${key}">${def.action}</button></div><div class="panel-body"><div class="toolbar"><div class="toolbar-left"><input class="search" data-action="search" value="${esc(search)}" placeholder="Search this section..."/><button class="btn" data-action="csv" data-key="${key}">Export CSV</button></div><button class="btn" data-action="form" data-key="${key}">+ New</button></div>${table(key,rows)}</div></section>`; }
function table(key,rows){ const def=MODULES[key]; if(!rows.length) return `<div class="empty"><div><strong>No live records yet.</strong><span>Add your first ${def.title.toLowerCase()} record. Dashboards and reports update automatically.</span></div></div>`; return `<div class="table-wrap"><table><thead><tr>${def.cols.map(col=>`<th>${head(col)}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr>${def.cols.map(col=>`<td>${cell(col,r)}</td>`).join('')}<td><button class="btn small" data-action="edit" data-key="${key}" data-id="${r.id}">Edit</button> <button class="btn small danger" data-action="delete" data-key="${key}" data-id="${r.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`; }
function reports(){ const m=metrics(), inv=state.inventory.reduce((s,x)=>s+num(x.qty)*num(x.unitCost),0), pipe=state.events.filter(x=>['Inquiry','Quoted','Booked','Prep Needed'].includes(x.status)), pipeVal=pipe.reduce((s,x)=>s+num(x.quote),0); return `<div class="grid4">${card('Month Sales',cash(m.sales),'Current calendar month.','info')}${card('Purchases',cash(m.purchases),'Current calendar month.','warn')}${card('Inventory Value',cash(inv),'Estimated value on hand.','neutral')}${card('Open Event Pipeline',cash(pipeVal),`${pipe.length} open event records.`,'ok')}</div><div class="two"><section class="panel"><div class="panel-head"><div><h3>Live Owner Summary</h3><p>All numbers recalculate after every record change.</p></div></div><div class="panel-body list">${item('Estimated profit',cash(m.profit),m.profit>=0?'Positive':'Negative',m.profit>=0?'ok':'bad')}${item('Estimated margin',pct(m.margin),'Margin',m.margin>=30?'Good':m.margin>=15?'Watch':'Weak',m.margin>=30?'ok':m.margin>=15?'warn':'bad')}${item('Labor as % of sales',pct(m.laborPct),'Labor',m.laborPct<=25?'ok':m.laborPct<=35?'warn':'bad')}${item('Total record count',String(Object.keys(MODULES).reduce((s,k)=>s+state[k].length,0)),'Records','info')}</div></section><section class="panel"><div class="panel-head"><div><h3>Export Center</h3><p>CSV outputs are generated from current live records.</p></div></div><div class="panel-body list">${Object.keys(MODULES).map(k=>`<div class="item"><div><strong>${MODULES[k].title}</strong><span>${state[k].length} current records.</span></div><button class="btn small" data-action="csv" data-key="${k}">CSV</button></div>`).join('')}</div></section></div>`; }
function syncPage(){ const readyExpenses=state.expenses.filter(x=>x.qbo==='Ready to Export').length, readyPurchases=state.purchases.filter(x=>x.qbo==='Ready to Export').length; return `<div class="grid4">${card('Sync Mode',syncLabel(),'Browser-tab live sync active.','ok')}${card('Revision',String(state.meta.revision||0),'Increments after every save/delete/import.','info')}${card('Last Saved',state.meta.lastSavedAt?fmtDT(state.meta.lastSavedAt):'Not yet','Most recent local write.','neutral')}${card('Accounting Ready',String(readyExpenses+readyPurchases),'Records marked ready to export.',readyExpenses+readyPurchases?'warn':'neutral')}</div><section class="panel"><div class="panel-head"><div><h3>Real-Time Scope</h3><p>The frontend is live-synchronized locally. Multi-device/team sync requires a database backend.</p></div></div><div class="panel-body list"><div class="notice"><strong>Active now:</strong> changes save immediately, recalculate all outputs, and synchronize across other open tabs/windows on this device.</div><div class="notice warn"><strong>Backend required for team sync:</strong> use Supabase, Firebase, or a custom API to synchronize across different devices/users.</div>${item('Sales, purchases, expenses, labor','Feed live dashboard and report calculations.','Live','ok')}${item('Inventory','Feeds reorder alerts and inventory value.','Live','ok')}${item('Menu costing','Feeds margin and profit outputs.','Live','ok')}<div class="toolbar-left"><button class="btn" data-action="backup">Download JSON Backup</button><button class="btn" data-action="csv" data-key="sales">Export Sales CSV</button><button class="btn" data-action="csv" data-key="expenses">Export Expenses CSV</button><button class="btn" data-action="csv" data-key="purchases">Export Purchases CSV</button></div></div></section>`; }
function settingsPage(){ return `<section class="panel"><div class="panel-head"><div><h3>Business Settings</h3><p>Changes save live and broadcast to open tabs.</p></div></div><div class="panel-body"><form id="settings" class="form-grid"><div class="field"><label>Tool Name</label><input class="input" name="businessName" value="${esc(state.settings.businessName)}"></div><div class="field"><label>Truck Name</label><input class="input" name="truckName" value="${esc(state.settings.truckName)}"></div><div class="field"><label>Default Tax Rate %</label><input class="input" name="taxRate" type="number" step=".01" value="${esc(state.settings.taxRate)}"></div><div class="field"><label>Accounting Mode</label><select name="accountingMode">${['Export Only','Backend Connector Planned','Connected Backend'].map(x=>`<option ${state.settings.accountingMode===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><button class="btn primary" type="submit">Save Settings</button></div></form></div></section><section class="panel" style="margin-top:18px"><div class="panel-head"><div><h3>Data Management</h3><p>Backup, restore, or clear live local data.</p></div></div><div class="panel-body list"><div class="notice"><strong>Current storage:</strong> browser local storage with live tab synchronization. No demo rows are seeded.</div><div class="toolbar-left"><button class="btn" data-action="backup">Download Backup JSON</button><label class="btn">Restore Backup<input type="file" accept="application/json" data-action="restore" hidden></label><button class="btn danger" data-action="clear">Clear All Records</button></div></div></section>`; }
function bind(){ document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>setActive(b.dataset.module)); document.querySelectorAll('[data-action="nav"]').forEach(b=>b.onclick=()=>{navOpen=!navOpen;render(true)}); document.querySelectorAll('[data-action="print"]').forEach(b=>b.onclick=()=>print()); document.querySelectorAll('[data-action="install"]').forEach(b=>b.onclick=()=>installPrompt?.prompt().finally(()=>{installPrompt=null;render(true)})); document.querySelectorAll('[data-action="backup"]').forEach(b=>b.onclick=backup); document.querySelectorAll('[data-action="csv"]').forEach(b=>b.onclick=()=>csv(b.dataset.key)); document.querySelectorAll('[data-action="form"]').forEach(b=>b.onclick=()=>openForm(b.dataset.key)); document.querySelectorAll('[data-action="edit"]').forEach(b=>b.onclick=()=>openForm(b.dataset.key,b.dataset.id)); document.querySelectorAll('[data-action="delete"]').forEach(b=>b.onclick=()=>deleteRow(b.dataset.key,b.dataset.id)); document.querySelectorAll('[data-action="restore"]').forEach(i=>i.onchange=restore); document.querySelectorAll('[data-action="clear"]').forEach(b=>b.onclick=clearAll); const s=document.querySelector('[data-action="search"]'); if(s) s.oninput=e=>{search=e.target.value; document.getElementById('root').innerHTML=tablePage(active); bind(); document.querySelector('[data-action="search"]')?.focus();}; const f=document.getElementById('settings'); if(f) f.onsubmit=e=>{e.preventDefault(); const fd=new FormData(f); commit(d=>{ d.settings={...d.settings,businessName:String(fd.get('businessName')||'Food Truck Command Center'),truckName:String(fd.get('truckName')||'Your Food Truck'),taxRate:num(fd.get('taxRate')),accountingMode:String(fd.get('accountingMode')||'Export Only')}; });}; }
function openForm(key,rowId){ const def=MODULES[key], existing=rowId?state[key].find(x=>x.id===rowId):null, modal=document.createElement('div'); modal.className='modal-bg'; modal.innerHTML=`<div class="modal"><div class="modal-head"><div><h3>${existing?'Edit '+def.title:def.action}</h3><p>Saving updates all dashboard and report outputs instantly.</p></div><button class="btn" data-close>Close</button></div><form id="record"><div class="modal-body form-grid">${def.fields.map(field=>fieldHtml(field,existing||{})).join('')}</div><div class="modal-foot"><button class="btn" type="button" data-close>Cancel</button><button class="btn primary" type="submit">Save Record</button></div></form></div>`; document.body.appendChild(modal); modal.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal.remove()); modal.onclick=e=>{ if(e.target===modal) modal.remove(); }; modal.querySelector('form').onsubmit=e=>{ e.preventDefault(); const fd=new FormData(e.target), next={}; def.fields.forEach(field=>{ const [name,,type]=field; const value=fd.get(name); next[name]=(type==='money'||type==='number')?num(value):String(value||'').trim(); }); commit(d=>{ if(existing){ const target=d[key].find(x=>x.id===rowId); if(target) Object.assign(target,next,{updatedAt:new Date().toISOString()}); } else { d[key].unshift(row(next)); } }); modal.remove(); }; modal.querySelector('input,select,textarea')?.focus(); }
function fieldHtml(field,record){ const [name,labelText,type,required,options]=field, value=record[name] ?? defaultValue(field), req=required?'required':''; if(type==='select') return `<div class="field"><label class="${required?'required':''}">${esc(labelText)}</label><select name="${name}" ${req}><option value="">Select...</option>${options.map(o=>`<option value="${esc(o)}" ${String(value)===o?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`; if(type==='textarea') return `<div class="field full"><label class="${required?'required':''}">${esc(labelText)}</label><textarea name="${name}" ${req}>${esc(value)}</textarea></div>`; return `<div class="field"><label class="${required?'required':''}">${esc(labelText)}</label><input class="input" name="${name}" type="${type==='money'?'number':type}" ${type==='money'||type==='number'?'step="0.01"':''} value="${esc(value)}" ${req}></div>`; }
function defaultValue(field){ const [name,,type,,options]=field; if(name==='date') return today(); if(name==='active') return 'Yes'; if(name==='qbo') return 'Not Ready'; if(name==='status') return options?.[0] || ''; if(type==='money'||type==='number') return ''; return ''; }
function deleteRow(key,rowId){ const target=state[key].find(x=>x.id===rowId); if(!target) return; if(confirm(`Delete ${target.name||target.item||target.date||'this record'}?`)) commit(d=>{ d[key]=d[key].filter(x=>x.id!==rowId); }); }
function clearAll(){ if(!confirm('Clear all live records from this browser? This cannot be undone unless you have a backup.')) return; commit(d=>{ Object.keys(MODULES).forEach(key=>{d[key]=[]}); }); }
function filtered(key){ const rows=[...state[key]]; if(!search.trim()) return rows; const q=search.toLowerCase(); return rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))); }
function cell(col,rowData){ if(col==='net') return cash(num(rowData.gross)-num(rowData.discounts)-num(rowData.refunds)); if(col==='balance') return cash(num(rowData.quote)-num(rowData.deposit)); if(col==='stockStatus') return statusPill(num(rowData.qty)<=0?'Out':num(rowData.qty)<=num(rowData.reorder)?'Reorder':'Good',num(rowData.qty)<=0?'bad':num(rowData.qty)<=num(rowData.reorder)?'warn':'ok'); if(col==='margin') return pct(itemMargin(rowData)); if(col==='profit') return cash(num(rowData.price)-num(rowData.cost)); if(col==='laborCost') return cash(num(rowData.hours)*num(rowData.rate)); const value=rowData[col]; if(MONEY_FIELDS.has(col)) return cash(value); if(col.toLowerCase().includes('date')||col==='expires') return fmtDate(value); if(['status','qbo','active'].includes(col)) return statusPill(value||'—',tone(value)); return esc(value||'—'); }
function metrics(){ const now=new Date(), month=now.getMonth(), year=now.getFullYear(), isMonth=value=>{ const d=new Date(value); return !isNaN(d) && d.getMonth()===month && d.getFullYear()===year; }; const todaySales=state.sales.filter(x=>x.date===today()).reduce((s,x)=>s+num(x.gross),0); const sales=state.sales.filter(x=>isMonth(x.date)).reduce((s,x)=>s+num(x.gross),0); const purchases=state.purchases.filter(x=>isMonth(x.date)).reduce((s,x)=>s+num(x.total),0); const expenses=state.expenses.filter(x=>isMonth(x.date)).reduce((s,x)=>s+num(x.amount),0); const labor=state.labor.filter(x=>isMonth(x.date)).reduce((s,x)=>s+num(x.hours)*num(x.rate),0); const profit=sales-purchases-expenses-labor; return {today:todaySales,sales,purchases,expenses,labor,profit,margin:sales?profit/sales*100:0,laborPct:sales?labor/sales*100:0}; }
function lowInventory(){ return state.inventory.filter(x=>num(x.qty)<=num(x.reorder)); }
function upcomingEvents(){ const now=new Date(); return state.events.filter(x=>x.date && new Date(x.date)>=now).sort((a,b)=>new Date(a.date)-new Date(b.date)); }
function followUps(){ const soon=new Date(); soon.setDate(soon.getDate()+7); return state.customers.filter(x=>x.followUp && new Date(x.followUp)<=soon && !['Lost','Completed'].includes(x.status)).sort((a,b)=>new Date(a.followUp)-new Date(b.followUp)); }
function menuInsights(){ return state.menu.map(x=>({name:x.name,profit:num(x.price)-num(x.cost),margin:itemMargin(x)})).sort((a,b)=>b.profit-a.profit).slice(0,5); }
function itemMargin(x){ return num(x.price)?(num(x.price)-num(x.cost))/num(x.price)*100:0; }
function card(labelText,value,note,toneName='neutral'){ return `<article class="card"><div class="card-label"><span>${esc(labelText)}</span><span class="pill ${toneName}">${tag(toneName)}</span></div><div class="card-value">${esc(value)}</div><div class="card-note">${esc(note)}</div></article>`; }
function item(title,body,badge,toneName='neutral'){ return `<div class="item"><div><strong>${esc(title)}</strong><span>${esc(body)}</span></div><span class="pill ${toneName}">${esc(badge)}</span></div>`; }
function progress(labelText,value){ const width=Math.max(0,Math.min(100,num(value))), toneName=value>=30?'ok':value>=15?'warn':'bad'; return `<div class="item"><div style="width:100%"><strong>${esc(labelText)} · ${pct(value)}</strong><div class="bar"><div class="bar-fill" style="width:${width}%"></div></div></div><span class="pill ${toneName}">${tag(toneName)}</span></div>`; }
function bars(rows){ if(!rows.length) return `<div class="empty"><div><strong>No chart data yet.</strong><span>Add sales to see live charts.</span></div></div>`; const max=Math.max(...rows.map(x=>x.value),1); return `<div class="chart">${rows.slice(0,8).map(x=>`<div class="chart-row"><div class="chart-label">${esc(x.label)}</div><div class="bar"><div class="bar-fill" style="width:${Math.max(4,x.value/max*100)}%"></div></div><div class="chart-value">${cash(x.value)}</div></div>`).join('')}</div>`; }
function groupBy(rows,key,valueKey){ const map=new Map(); rows.forEach(row=>{ const labelValue=row[key]||'Uncategorized'; map.set(labelValue,(map.get(labelValue)||0)+num(row[valueKey])); }); return [...map].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value); }
function csv(key){ const def=MODULES[key], fields=[...new Set([...def.fields.map(f=>f[0]),...def.cols])]; const body=[fields.join(',')].concat(state[key].map(record=>fields.map(field=>csvEsc(csvValue(field,record))).join(','))).join('\n'); download(`${key}-${today()}.csv`,body,'text/csv'); }
function csvValue(field,record){ if(field==='net') return num(record.gross)-num(record.discounts)-num(record.refunds); if(field==='balance') return num(record.quote)-num(record.deposit); if(field==='margin') return itemMargin(record); if(field==='profit') return num(record.price)-num(record.cost); if(field==='laborCost') return num(record.hours)*num(record.rate); return record[field]??''; }
function backup(){ download(`food-truck-command-center-live-backup-${today()}.json`,JSON.stringify(state,null,2),'application/json'); }
function restore(event){ const file=event.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ try{ const imported=normalize(JSON.parse(reader.result)); commit(d=>{ Object.assign(d,imported,{meta:{...d.meta,revision:(Number(d.meta.revision)||0)+1,lastSavedAt:new Date().toISOString(),lastSavedBy:CLIENT_ID}}); }); } catch { alert('Could not restore this backup file.'); } }; reader.readAsText(file); }
function download(filename,text,type){ const blob=new Blob([text],{type}), url=URL.createObjectURL(blob), link=document.createElement('a'); link.href=url; link.download=filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
function fmtDate(value){ if(!value) return '—'; const date=new Date(value); return isNaN(date)?esc(value):date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}); }
function fmtDT(value){ if(!value) return '—'; const date=new Date(value); return isNaN(date)?String(value):date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}); }
function cash(value){ return new Intl.NumberFormat(undefined,{style:'currency',currency:state.settings.currency||'USD',maximumFractionDigits:0}).format(num(value)); }
function pct(value){ return `${num(value).toFixed(1)}%`; }
function num(value){ const n=Number(value); return Number.isFinite(n)?n:0; }
function statusPill(value,toneName){ return `<span class="pill ${toneName}">${esc(value)}</span>`; }
function tone(value){ const v=String(value||'').toLowerCase(); if(['booked','completed','active','exported','yes','good'].some(x=>v.includes(x))) return 'ok'; if(['quoted','prep','ready','contacted','seasonal','reorder'].some(x=>v.includes(x))) return 'warn'; if(['lost','cancelled','needs review','out','no'].some(x=>v.includes(x))) return 'bad'; if(['new','inquiry'].some(x=>v.includes(x))) return 'info'; return 'neutral'; }
function tag(toneName){ return {ok:'Good',warn:'Watch',bad:'Alert',info:'Live',neutral:'Open'}[toneName]||'Open'; }
function label(key){ return {dashboard:'Dashboard',customers:'CRM',sync:'Live Sync'}[key] || MODULES[key]?.title || key; }
function head(key){ return {gross:'Gross Sales',net:'Net Sales',type:'Service',customer:'Customer',guests:'Guests',quote:'Quote',balance:'Balance',qty:'Qty',reorder:'Reorder',stockStatus:'Status',unitCost:'Cost / Unit',expires:'Expires',price:'Sell Price',cost:'Food Cost',profit:'Profit',prep:'Prep Min',total:'Total Cost',qbo:'Accounting',rate:'Rate',laborCost:'Labor Cost',followUp:'Follow-Up'}[key] || key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()); }
function csvEsc(value){ value=String(value??''); return /[",\n]/.test(value)?`"${value.replace(/"/g,'""')}"`:value; }
function esc(value){ return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); }
function syncLabel(){ return channel ? 'Live local sync on' : 'Live local storage sync'; }
function registerSW(){ if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn)); }
