import { useDeferredValue, useMemo, useState } from 'react';
import { Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { Modal } from '../components/Modal.jsx';
import { GENERIC_MODULES, MONEY_FIELDS } from '../config/modules.js';
import { createRow, dollars, numberValue } from '../lib/format.js';
import { useAppStore } from '../lib/store.jsx';
export function GenericModulePage({moduleKey}){const def=GENERIC_MODULES[moduleKey];const{state,commit}=useAppStore();const[query,setQuery]=useState('');const deferred=useDeferredValue(query);const[editing,setEditing]=useState(undefined);const[form,setForm]=useState({});const rows=useMemo(()=>{const source=state[moduleKey]||[];const q=deferred.trim().toLowerCase();return q?[...source].reverse().filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))):[...source].reverse();},[state,moduleKey,deferred]);const open=row=>{setEditing(row||null);setForm(row?{...row}:Object.fromEntries(def.fields.map(([key,,,,options])=>[key,options?.[0]||''])));};const close=()=>{setEditing(undefined);setForm({});};const save=()=>{for(const[key,label,,required]of def.fields)if(required&&!String(form[key]??'').trim())return alert(`${label} is required.`);commit(d=>{if(editing){const index=d[moduleKey].findIndex(r=>r.id===editing.id);if(index>=0)d[moduleKey][index]={...d[moduleKey][index],...form,updatedAt:new Date().toISOString()};}else d[moduleKey].push(createRow(form));});close();};const remove=row=>{if(!confirm('Delete this record?'))return;commit(d=>{d[moduleKey]=d[moduleKey].filter(i=>i.id!==row.id);});};return <><section className="surface"><div className="section-head"><div><h2>{def.title}</h2><p>{state[moduleKey].length} saved record{state[moduleKey].length===1?'':'s'}.</p></div><button className="button primary" type="button" onClick={()=>open(null)}><Plus size={16}/>{def.action}</button></div><div className="toolbar"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${def.title.toLowerCase()}`}/></label><span>{rows.length} shown</span></div>{rows.length?<div className="table-scroll"><table className="data-table"><thead><tr>{def.cols.map(c=><th key={c}>{humanize(c)}</th>)}<th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{def.cols.map(c=><td key={c}>{formatCell(moduleKey,c,row,state.settings.currency)}</td>)}<td><div className="row-actions"><button className="icon-button" type="button" onClick={()=>open(row)} aria-label="Edit"><Pencil size={15}/></button><button className="icon-button danger" type="button" onClick={()=>remove(row)} aria-label="Delete"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><strong>No records yet</strong><p>Add the first {def.title.toLowerCase()} record.</p></div>}</section>{editing!==undefined?<Modal title={editing?`Edit ${def.title}`:def.action} onClose={close} actions={<><button className="button secondary" type="button" onClick={close}>Cancel</button><button className="button primary" type="button" onClick={save}>Save</button></>}><div className="form-grid">{def.fields.map(field=><FormField key={field[0]} field={field} value={form[field[0]]??''} onChange={value=>setForm(c=>({...c,[field[0]]:value}))}/>)}</div></Modal>:null}</>;}
function FormField({field,value,onChange}){const[,label,type,required,options]=field;let control;if(type==='select')control=<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>;else if(type==='textarea')control=<textarea value={value} onChange={e=>onChange(e.target.value)}/>;else control=<input type={type==='money'?'text':type} inputMode={type==='money'?'decimal':undefined} value={value} onChange={e=>onChange(e.target.value)}/>;return <label className={`field ${type==='textarea'?'full':''}`}><span>{label}{required?' *':''}</span>{control}</label>;}
function formatCell(moduleKey,key,row,currency){if(key==='laborCost')return dollars(numberValue(row.hours)*numberValue(row.rate),currency);if(key==='profit'&&moduleKey==='menu')return dollars(numberValue(row.price)-numberValue(row.cost),currency);if(key==='margin'&&moduleKey==='menu')return `${numberValue(row.price)?((numberValue(row.price)-numberValue(row.cost))/numberValue(row.price)*100).toFixed(1):'0.0'}%`;if(MONEY_FIELDS.has(key))return dollars(row[key],currency);return String(row[key]??'—');}
function humanize(v){return v.replace(/([A-Z])/g,' $1').replace(/^./,l=>l.toUpperCase());}
