create extension if not exists pgcrypto;

create table if not exists public.live_orders (
  id uuid primary key default gen_random_uuid(),
  square_order_id text not null unique,
  square_payment_id text,
  location_id text,
  ticket_number bigint generated by default as identity unique,
  customer_name text,
  status text not null default 'active' check (status in ('active','ready','complete','canceled')),
  square_state text,
  payment_status text,
  total_cents bigint not null default 0,
  currency text not null default 'USD',
  items jsonb not null default '[]'::jsonb,
  source_created_at timestamptz,
  last_square_event_at timestamptz,
  ready_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists live_orders_status_source_created_idx on public.live_orders(status, source_created_at, created_at);
create index if not exists live_orders_square_payment_idx on public.live_orders(square_payment_id);

create table if not exists public.processed_square_events (
  event_id text primary key,
  event_type text not null,
  square_order_id text,
  received_at timestamptz not null default now()
);

create index if not exists processed_square_events_received_idx on public.processed_square_events(received_at desc);

create table if not exists public.kiosk_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  label text not null default 'Truck laptop',
  authorized_until timestamptz not null,
  authorized_at timestamptz not null default now()
);

alter table public.live_orders enable row level security;
alter table public.processed_square_events enable row level security;
alter table public.kiosk_sessions enable row level security;


create or replace function public.kiosk_is_authorized()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.kiosk_sessions s
    where s.user_id = auth.uid()
      and s.authorized_until > now()
  );
$$;

revoke all on function public.kiosk_is_authorized() from public;
grant execute on function public.kiosk_is_authorized() to authenticated;

create policy "authorized kiosks can read live orders"
on public.live_orders for select
to authenticated
using (public.kiosk_is_authorized());

create policy "authorized kiosks can update workflow status"
on public.live_orders for update
to authenticated
using (public.kiosk_is_authorized())
with check (public.kiosk_is_authorized());

grant select on public.live_orders to authenticated;
grant update(status, ready_at, completed_at, updated_at) on public.live_orders to authenticated;

grant usage, select on sequence public.live_orders_ticket_number_seq to service_role;

create or replace function public.set_live_order_updated_at()
returns trigger
language plpgsql
as $$
begin
  if current_user <> 'service_role' then
    if (old.status = 'active' and new.status <> 'ready')
      or (old.status = 'ready' and new.status <> 'complete')
      or old.status in ('complete','canceled')
      or new.square_order_id is distinct from old.square_order_id then
      raise exception 'Invalid order status transition';
    end if;
    new.ready_at = case when new.status = 'ready' then now() else old.ready_at end;
    new.completed_at = case when new.status = 'complete' then now() else old.completed_at end;
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_live_order_updated_at on public.live_orders;
create trigger set_live_order_updated_at
before update on public.live_orders
for each row execute function public.set_live_order_updated_at();

-- Realtime emits changes only after the table is part of the publication.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='live_orders'
  ) then
    alter publication supabase_realtime add table public.live_orders;
  end if;
end $$;

-- Clients should receive enough UPDATE data to re-fetch deterministically.
-- Default replica identity avoids broadcasting an entire previous order image.
